# Generated by Django 4.2.2 on 2023-06-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='info',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='info',
            name='re_password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
