# Generated by Django 4.2.2 on 2023-07-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('password1', models.CharField(max_length=30)),
            ],
        ),
    ]
