# Generated by Django 4.2.2 on 2023-06-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Phno', models.IntegerField(default='')),
                ('Email', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
